Make PIN entry optional
cedricbahirwe/dialer pull request #97
Opened 2023-07-17 20:32 UTC by nshutinicolas

## Description

Currently MTN does not support PIN to be appended to the USSD string for mount equal or greater than 100 when purchasing airtime but Dialer still requires the PIN.

## The Fix
This PR:
- Makes the PIN entry optional for airtime purchase.
- Adds a new file `AppConstants` to use for all app constants
- Updates unit tests

2023-07-17 20:34 UTC, nshutinicolas commented on Dialer/Dialer/View Models/MainViewModel.swift
> +    }
Moved this here to make it easy for testing in the near future

2023-07-20 08:59 UTC, cedricbahirwe commented
Did you pull the latest changes before pushing ?

2023-07-20 09:16 UTC, cedricbahirwe requested changes
Welcomed PR 🙏 , Check minor comments

2023-07-20 09:16 UTC, cedricbahirwe commented on Dialer/DialerTests/Test Cases/ModelTests/PurchaseDetailModelTests.swift
> +    func testPinnedPurchase_amountInRangeForPinAppending() throws {
Adopt general Naming convention

2023-07-20 09:16 UTC, cedricbahirwe commented on Dialer/DialerTests/Test Cases/ModelTests/PurchaseDetailModelTests.swift
> +    func testPinnedPurchase_amountOutOfRangeForPinAppending() throws {
Adopt naming convetion here as well

2023-07-20 09:16 UTC, cedricbahirwe commented on Dialer/Dialer/Views/Main/PurchaseDetailView.swift
> +                        .disabled(!data.validAmount)
`hasValidAmount` (this sounds like a boolean) vs `validAmount` (this seems to sound like a number)?!

2023-07-20 09:16 UTC, cedricbahirwe commented on Dialer/Dialer/View Models/MainViewModel.swift
> +    }
Agreed, but I think the naming can be improve, check the comments below

2023-07-20 09:16 UTC, cedricbahirwe commented on Dialer/Dialer/Utilities/AppConstants.swift
> +struct AppConstants {
Why a `struct`, why not an `enum` ??,

In this case of using a struct , someone might assume that the AppConstants can be initialized (`AppConstants()`), which is not correct 

If your data has multiple properties and represents objects with various attributes, use `struct`.
If your data has a limited set of related values or represents mutually exclusive options, use `enum`.

2023-07-21 18:29 UTC, nshutinicolas commented on Dialer/DialerTests/Test Cases/ModelTests/PurchaseDetailModelTests.swift
> +    func testPinnedPurchase_amountInRangeForPinAppending() throws {
Sorry about that. On it🫡

2023-07-21 18:29 UTC, nshutinicolas commented on Dialer/Dialer/Views/Main/PurchaseDetailView.swift
> +                        .disabled(!data.validAmount)
Sure, it sounds better

2023-07-21 18:32 UTC, nshutinicolas commented on Dialer/Dialer/Utilities/AppConstants.swift
> +struct AppConstants {
It is a struct as it holds different types.
Let me make the init private then

2023-07-21 18:51 UTC, nshutinicolas commented on Dialer/Dialer/Utilities/AppConstants.swift
> +    private init() { }
Made the init private to avoid initialization

2023-07-25 10:19 UTC, cedricbahirwe approved these changes
LGTM🔥

2023-07-25 10:20 UTC, merged